# Uncomment the next line to define a global platform for your project


target 'Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '10.0'

  # Pods for AgoraLog
  pod 'AgoraLog', :path => '../'
end

target 'Sample-Mac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :osx, '10.12'

  # Pods for AgoraLog
  pod 'AgoraLog', :path => '../'
end
